# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect and rewrite rules
[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# For SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
